package com.mycompany.tutorhub_enterprise.client.ai;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;

public final class AiLongTermMemoryStore {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
    private static final int MAX_ITEMS = 24;
    private static final int MAX_NOTE_CHARS = 700;
    private static final int MAX_CONTEXT_CHARS = 3200;
    private static final int MAX_DISPLAY_ITEMS = 8;

    private final Path memoryFile;

    public AiLongTermMemoryStore(String userId, String conversationId) {
        this.memoryFile = memoryRoot()
                .resolve(safeSegment(userId) + "_" + safeSegment(conversationId) + ".json");
    }

    public synchronized MemorySnapshot snapshot() {
        List<MemoryItem> items = readItems();
        return new MemorySnapshot(items, buildContext(items));
    }

    public synchronized MemorySnapshot add(String note) {
        return addManual(note).getSnapshot();
    }

    public synchronized MemoryWriteResult addAuto(String note, String source) {
        return addInternal(note, true, cleanSource(source));
    }

    private synchronized MemoryWriteResult addManual(String note) {
        return addInternal(note, false, "user");
    }

    private MemoryWriteResult addInternal(String note, boolean autoGenerated, String source) {
        String normalized = normalize(note);
        if (normalized.isEmpty()) {
            return MemoryWriteResult.skipped("Memory note is empty.", snapshot());
        }
        if (autoGenerated && looksSensitive(normalized)) {
            return MemoryWriteResult.skipped("Memory note was not saved because it may contain sensitive data.", snapshot());
        }
        List<MemoryItem> items = readItems();
        if (containsDuplicate(items, normalized)) {
            return MemoryWriteResult.skipped("Memory note already exists.", new MemorySnapshot(items, buildContext(items)));
        }
        items.add(new MemoryItem(UUID.randomUUID().toString(), normalized, System.currentTimeMillis(),
                autoGenerated, source));
        items.sort(Comparator.comparingLong(MemoryItem::getCreatedAt));
        while (items.size() > MAX_ITEMS) {
            items.remove(0);
        }
        writeItems(items);
        return MemoryWriteResult.saved(new MemorySnapshot(items, buildContext(items)));
    }

    public synchronized MemorySnapshot clear() {
        writeItems(new ArrayList<>());
        return new MemorySnapshot(new ArrayList<>(), "");
    }

    public synchronized MemoryWriteResult update(String id, String note) {
        String cleanId = normalizeProvidedId(id);
        String normalized = normalize(note);
        if (cleanId.isEmpty()) {
            return MemoryWriteResult.skipped("Memory id is required.", snapshot());
        }
        if (normalized.isEmpty()) {
            return MemoryWriteResult.skipped("Memory note is empty.", snapshot());
        }
        if (looksSensitive(normalized)) {
            return MemoryWriteResult.skipped("Memory note was not saved because it may contain sensitive data.", snapshot());
        }
        List<MemoryItem> items = readItems();
        boolean updated = false;
        List<MemoryItem> next = new ArrayList<>();
        for (MemoryItem item : items) {
            if (item != null && cleanId.equals(item.getId())) {
                next.add(new MemoryItem(item.getId(), normalized, item.getCreatedAt(),
                        item.isAutoGenerated(), item.getSource()));
                updated = true;
            } else if (item != null) {
                next.add(item);
            }
        }
        if (!updated) {
            return MemoryWriteResult.skipped("Memory note was not found.", new MemorySnapshot(items, buildContext(items)));
        }
        writeItems(next);
        return MemoryWriteResult.saved(new MemorySnapshot(next, buildContext(next)));
    }

    public synchronized MemoryWriteResult remove(String id) {
        String cleanId = normalizeProvidedId(id);
        if (cleanId.isEmpty()) {
            return MemoryWriteResult.skipped("Memory id is required.", snapshot());
        }
        List<MemoryItem> items = readItems();
        List<MemoryItem> next = new ArrayList<>();
        boolean removed = false;
        for (MemoryItem item : items) {
            if (item != null && cleanId.equals(item.getId())) {
                removed = true;
            } else if (item != null) {
                next.add(item);
            }
        }
        if (!removed) {
            return MemoryWriteResult.skipped("Memory note was not found.", new MemorySnapshot(items, buildContext(items)));
        }
        writeItems(next);
        return MemoryWriteResult.saved(new MemorySnapshot(next, buildContext(next)));
    }

    private String buildContext(List<MemoryItem> items) {
        if (items == null || items.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        for (int i = items.size() - 1; i >= 0; i--) {
            MemoryItem item = items.get(i);
            String line = "- " + item.getContent() + "\n";
            if (sb.length() + line.length() > MAX_CONTEXT_CHARS) {
                break;
            }
            sb.insert(0, line);
        }
        return sb.toString().trim();
    }

    private List<MemoryItem> readItems() {
        if (!Files.exists(memoryFile)) {
            return new ArrayList<>();
        }
        try {
            String json = Files.readString(memoryFile, StandardCharsets.UTF_8);
            MemoryFile file = GSON.fromJson(json, MemoryFile.class);
            if (file == null || file.items == null) {
                return new ArrayList<>();
            }
            List<MemoryItem> items = new ArrayList<>();
            for (MemoryItem item : file.items) {
                if (item != null && item.getContent() != null && !item.getContent().trim().isEmpty()) {
                    items.add(new MemoryItem(
                            cleanId(item.getId()),
                            normalize(item.getContent()),
                            item.getCreatedAt(),
                            item.isAutoGenerated(),
                            cleanSource(item.getSource())));
                }
            }
            items.sort(Comparator.comparingLong(MemoryItem::getCreatedAt));
            while (items.size() > MAX_ITEMS) {
                items.remove(0);
            }
            return items;
        } catch (Exception ignored) {
            return new ArrayList<>();
        }
    }

    private void writeItems(List<MemoryItem> items) {
        try {
            Files.createDirectories(memoryFile.getParent());
            MemoryFile file = new MemoryFile();
            file.items = items == null ? new ArrayList<>() : new ArrayList<>(items);
            Path temp = memoryFile.resolveSibling(memoryFile.getFileName().toString() + ".tmp");
            Files.writeString(temp, GSON.toJson(file), StandardCharsets.UTF_8);
            Files.move(temp, memoryFile, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException ex) {
            try {
                MemoryFile file = new MemoryFile();
                file.items = items == null ? new ArrayList<>() : new ArrayList<>(items);
                Files.createDirectories(memoryFile.getParent());
                Files.writeString(memoryFile, GSON.toJson(file), StandardCharsets.UTF_8);
            } catch (IOException ignored) {
                // Long-term memory is optional; chat must keep working even if local storage fails.
            }
        }
    }

    private static Path memoryRoot() {
        String home = System.getProperty("user.home");
        if (home == null || home.trim().isEmpty()) {
            home = ".";
        }
        return Paths.get(home, ".tutorhub", "ai-memory");
    }

    private static String safeSegment(String value) {
        String clean = value == null ? "default" : value.trim();
        if (clean.isEmpty()) {
            clean = "default";
        }
        return clean.replaceAll("[^a-zA-Z0-9._-]", "_");
    }

    private static String cleanId(String id) {
        if (id == null || id.trim().isEmpty()) {
            return UUID.randomUUID().toString();
        }
        return id.trim();
    }

    private static String normalizeProvidedId(String id) {
        return id == null ? "" : id.trim();
    }

    private static String cleanSource(String source) {
        String clean = source == null ? "" : source.replaceAll("\\s+", " ").trim();
        if (clean.isEmpty()) {
            return "agent";
        }
        if (clean.length() <= 80) {
            return clean;
        }
        return clean.substring(0, 80).trim();
    }

    private static String normalize(String value) {
        if (value == null) {
            return "";
        }
        String normalized = value.replaceAll("\\s+", " ").trim();
        if (normalized.length() <= MAX_NOTE_CHARS) {
            return normalized;
        }
        return normalized.substring(0, MAX_NOTE_CHARS).trim() + "...";
    }

    private static boolean containsDuplicate(List<MemoryItem> items, String normalized) {
        if (items == null || normalized == null) {
            return false;
        }
        String comparable = normalized.trim().toLowerCase();
        return items.stream()
                .filter(item -> item != null && item.getContent() != null)
                .map(item -> item.getContent().trim().toLowerCase())
                .anyMatch(comparable::equals);
    }

    private static boolean looksSensitive(String value) {
        if (value == null) {
            return false;
        }
        String lower = value.toLowerCase();
        return lower.contains("password")
                || lower.contains("passwd")
                || lower.contains("api key")
                || lower.contains("apikey")
                || lower.contains("secret")
                || lower.contains("token")
                || lower.contains("credential")
                || lower.contains("private key")
                || lower.contains("-----begin")
                || lower.contains("bearer ")
                || lower.contains("hf_")
                || lower.contains("sk-");
    }

    private static final class MemoryFile {
        private List<MemoryItem> items = new ArrayList<>();
    }

    public static final class MemorySnapshot {
        private final List<MemoryItem> items;
        private final String context;

        private MemorySnapshot(List<MemoryItem> items, String context) {
            this.items = items == null ? new ArrayList<>() : new ArrayList<>(items);
            this.context = context == null ? "" : context;
        }

        public List<MemoryItem> getItems() {
            return Collections.unmodifiableList(items);
        }

        public String getContext() {
            return context;
        }

        public int getCount() {
            return items.size();
        }

        public List<MemoryItem> getDisplayItems() {
            int start = Math.max(0, items.size() - MAX_DISPLAY_ITEMS);
            return Collections.unmodifiableList(new ArrayList<>(items.subList(start, items.size())));
        }
    }

    public static final class MemoryItem {
        private String id;
        private String content;
        private long createdAt;
        private boolean autoGenerated;
        private String source;

        private MemoryItem() {
            this("", "", 0, false, "user");
        }

        private MemoryItem(String id, String content, long createdAt) {
            this(id, content, createdAt, false, "user");
        }

        private MemoryItem(String id, String content, long createdAt, boolean autoGenerated, String source) {
            this.id = id;
            this.content = content;
            this.createdAt = createdAt <= 0 ? System.currentTimeMillis() : createdAt;
            this.autoGenerated = autoGenerated;
            this.source = cleanSource(source);
        }

        public String getId() {
            return id;
        }

        public String getContent() {
            return content;
        }

        public long getCreatedAt() {
            return createdAt;
        }

        public boolean isAutoGenerated() {
            return autoGenerated;
        }

        public String getSource() {
            return source == null ? "" : source;
        }
    }

    public static final class MemoryWriteResult {
        private final boolean saved;
        private final String message;
        private final MemorySnapshot snapshot;

        private MemoryWriteResult(boolean saved, String message, MemorySnapshot snapshot) {
            this.saved = saved;
            this.message = message == null ? "" : message;
            this.snapshot = snapshot == null ? new MemorySnapshot(new ArrayList<>(), "") : snapshot;
        }

        private static MemoryWriteResult saved(MemorySnapshot snapshot) {
            return new MemoryWriteResult(true, "Memory note saved.", snapshot);
        }

        private static MemoryWriteResult skipped(String message, MemorySnapshot snapshot) {
            return new MemoryWriteResult(false, message, snapshot);
        }

        public boolean isSaved() {
            return saved;
        }

        public String getMessage() {
            return message;
        }

        public MemorySnapshot getSnapshot() {
            return snapshot;
        }
    }
}
